# Generated by Django 3.2.8 on 2021-11-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_film_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='film_photos/'),
        ),
    ]
